# Hyprpaper configuration

# https://alphacoders.com/

# Preload the image once, then assign it to each monitor defined in Hyprland.
preload = ~/.config/wallpapers/1349198.png

# Apply wallpaper to specific monitors (use exact monitor names from Hyprland)
wallpaper = desc:LG Display 0x0709,~/.config/wallpapers/1349198.png
wallpaper = desc:LG Electronics LG ULTRAGEAR+ 408NTPCCZ200,~/.config/wallpapers/1349198.png
wallpaper = desc:Philips Consumer Electronics Company PHL 230B8Q 0x00000035,~/.config/wallpapers/1349198.png
wallpaper = desc:Microstep MSI AG321CQR DB4H081402289,~/.config/wallpapers/1349198.png
wallpaper = HDMI-A-1,~/.config/wallpapers/1349198.png
# Optional: disable splash to avoid the default Hyprpaper splash screen
splash = false